version: '3.8'

services:

  clair_server:
    image: uschuster/clair:latest
    depends_on:
      - mongo
    environment:
      # Use modern UUID format.
      # See https://pymongo.readthedocs.io/en/stable/examples/uuid.html#configuring-uuid-representation
      # See https://medium.com/@sylwester.kardziejonek/how-to-configure-pymongo-uuid-representation-globally-19e61c50a1b2
      CLAIR_MONGODB_CONNECTION: 'mongodb://mongo/clair?uuidRepresentation=standard'
      FLASK_ENV: 'production'
      FLASK_DEBUG: 1
      CLAIR_STAGING: 1
      SENTRY_ACTIVE: 1
    networks:
      - frontend
      - backend
    deploy:
      labels:
        - traefik.enable=true
        - traefik.docker.network=clair_frontend
        - traefik.http.routers.clair-server.rule=PathPrefix(`/api/ingest`)
        - traefik.http.routers.clair-server.priority=30
        - traefik.http.services.clair-server.loadbalancer.server.port=5000
        - traefik.http.routers.clair-server.tls=true
        - traefik.http.routers.clair-server.tls.domains[0].main=${CLAIR_DOMAIN}
        - traefik.http.routers.clair-server.tls.certresolver=leresolver

  mongo:
    image: mongo:latest
    environment:
      MONGO_INITDB_DATABASE: "clair"
    volumes:
      - clair-data:/data/db
    networks:
      - backend

volumes:
  clair-data:

