resources:
  - ../../base
  - 95-cert-issuer.yaml

patchesStrategicMerge:
  - add_tls.yaml

configMapGenerator:
  - name: clair-config-map
    namespace: clair-berlin
    behavior: replace
    envs:
      - config.env

secretGenerator:
  - name: db-secret
    namespace: clair-berlin
    behavior: replace
    files:
      - secrets/sql-password.txt
  - name: managair-secret
    namespace: clair-berlin
    behavior: replace
    files:
      - secrets/managair-secret-key.txt
      - secrets/sql-password.txt
      - secrets/sentry-url.txt
      - secrets/smtp-password.txt
  - name: ingestair-secret
    namespace: clair-berlin
    behavior: replace
    files:
      - secrets/ingestair-secret-key.txt
      - secrets/sql-password.txt
      - secrets/smtp-password.txt
  - name: clairchen-forwarder-v2-secret
    namespace: clair-berlin
    behavior: replace
    files:
      - secrets/clairchen-forwarder-v2-access-key.txt
  - name: ers-forwarder-v2-secret
    namespace: clair-berlin
    behavior: replace
    files:
      - secrets/ers-forwarder-v2-access-key.txt
  - name: clairchen-forwarder-v3-secret
    namespace: clair-berlin
    behavior: replace
    files:
      - secrets/clairchen-forwarder-v3-access-key.txt
  - name: ers-forwarder-v3-secret
    namespace: clair-berlin
    behavior: replace
    files:
      - secrets/ers-forwarder-v3-access-key.txt
