
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: ingestair
  name: ingestair
  namespace: clair-berlin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ingestair
  strategy: {}
  template:
    metadata:
      labels:
        app: ingestair
    spec:
      containers:
        - args:
            - python
            - manage.py
            - runserver
            - 0.0.0.0:8888
          env:
            - name: SECRET_KEY_FILE
              value: "/var/secrets/ingestair-secret-key/ingestair-secret-key"
            - name: SENTRY
              value: "0"
            - name: SENTRY_URL_FILE
              value: "/var/secrets/sentry-url/sentry-url"
            - name: DEBUG
              value: "0"
            - name: DJANGO_LOG_LEVEL
              valueFrom:
                configMapKeyRef:
                  name: config-map
                  key: django-log-level
            - name: DJANGO_DB_LOG_LEVEL
              valueFrom:
                configMapKeyRef:
                  name: config-map
                  key: django-db-log-level
            - name: LOG_LEVEL
              valueFrom:
                configMapKeyRef:
                  name: config-map
                  key: log-level
            - name: SQL_ENGINE
              value: "django.db.backends.postgresql"
            - name: SQL_HOST
              value: "db"
            - name: SQL_PORT
              value: "5432"
            - name: SQL_DATABASE
              valueFrom:
                configMapKeyRef:
                  name: config-map
                  key: sql-database
            - name: SQL_USER
              valueFrom:
                configMapKeyRef:
                  name: config-map
                  key: sql-user
            - name: SQL_PASSWORD_FILE
              value: "/var/secrets/sql-password/sql-password"
          # XXX why doesn't this work?
          # - name: SQL_PASSWORD
          #   valueFrom:
          #     secretKeyRef:
          #       name: sql-password
          #       key: sql-password
            - name: DATABASE
              value: "postgresql"
            - name: DB_MIGRATE
              valueFrom:
                configMapKeyRef:
                  name: config-map
                  key: ingestair-db-migrate
            - name: COLLECT_STATIC_FILES
              value: "false"
            - name: NODE_FIDELITY
              value: "1"
            - name: DJANGO_ALLOWED_HOSTS
              value: "ingestair localhost 127.0.0.1 [::1]"
            - name: EMAIL_HOST
              valueFrom:
                configMapKeyRef:
                  name: config-map
                  key: email-host
            - name: EMAIL_PORT
              valueFrom:
                configMapKeyRef:
                  name: config-map
                  key: email-port
            - name: EMAIL_HOST_USER
              valueFrom:
                configMapKeyRef:
                  name: config-map
                  key: email-host-user
            - name: EMAIL_HOST_PASSWORD_FILE
              value: "/var/secrets/smtp-password/smtp-password"
            - name: EMAIL_USE_TLS
              valueFrom:
                configMapKeyRef:
                  name: config-map
                  key: email-use-tls
            - name: DEFAULT_FROM_EMAIL
              valueFrom:
                configMapKeyRef:
                  name: config-map
                  key: default-from-email
          image: clairberlin/managair:0.6.5
          name: ingestair-server
          resources: {}
          volumeMounts:
            - mountPath: "/var/secrets/ingestair-secret-key"
              name: ingestair-secret-key
              readOnly: true
            - mountPath: "/var/secrets/sentry-url"
              name: sentry-url
              readOnly: true
            - mountPath: "/var/secrets/sql-password"
              name: sql-password
              readOnly: true
            - mountPath: "/var/secrets/smtp-password"
              name: smtp-password
              readOnly: true
      restartPolicy: Always
      volumes:
        - name: ingestair-secret-key
          secret:
            items:
              - key: ingestair-secret-key
                path: ingestair-secret-key
            secretName: ingestair-secret-key
        - name: sentry-url
          secret:
            items:
              - key: sentry-url
                path: sentry-url
            secretName: sentry-url
        - name: sql-password
          secret:
            items:
              - key: sql-password
                path: sql-password
            secretName: sql-password
        - name: smtp-password
          secret:
            items:
              - key: smtp-password
                path: smtp-password
            secretName: smtp-password
